/**
 * Predefined Department IDs
 * 
 * Auto-generated by setup script on 2025-10-07T20:24:49.033Z
 * These IDs are from Firestore and should not be changed manually.
 * 
 * Location: src/config/departmentIds.ts
 * Purpose: Central reference for predefined department IDs
 */

export const DEPARTMENT_IDS = {
  GROUND_SUPPORT: 'TcDeuU506HIfq5V7RVr2',
  LOGISTICS: 'gv8lPOzXJjcK3bH9DI5o',
  MEDICAL: 'ogZrQxt5mEfH8171ANpJ'
} as const;

/**
 * Department names in Hebrew mapped to their IDs
 */
export const DEPARTMENT_NAMES: Record<string, string> = {
  [DEPARTMENT_IDS.GROUND_SUPPORT]: 'שירותי קרקע',
  [DEPARTMENT_IDS.LOGISTICS]: 'לוגיסטיקה',
  [DEPARTMENT_IDS.MEDICAL]: 'מרפאה'
};

/**
 * Department names in English
 */
export const DEPARTMENT_NAMES_EN: Record<string, string> = {
  [DEPARTMENT_IDS.GROUND_SUPPORT]: 'Ground Support',
  [DEPARTMENT_IDS.LOGISTICS]: 'Logistics',
  [DEPARTMENT_IDS.MEDICAL]: 'Medical'
};

/**
 * Type for department IDs
 */
export type DepartmentId = typeof DEPARTMENT_IDS[keyof typeof DEPARTMENT_IDS];

/**
 * Check if a department ID is predefined
 */
export function isPredefinedDepartment(departmentId: string): boolean {
  return Object.values(DEPARTMENT_IDS).includes(departmentId as DepartmentId);
}

/**
 * Get department name by ID
 */
export function getDepartmentName(departmentId: string): string {
  return DEPARTMENT_NAMES[departmentId] || 'מחלקה לא ידועה';
}

/**
 * Get department English name by ID
 */
export function getDepartmentNameEn(departmentId: string): string {
  return DEPARTMENT_NAMES_EN[departmentId] || 'Unknown Department';
}
